config/routes.rb
Rails.application.routes.draw do

  root "top#index"
  resources :topics, only: [:index, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create,:edit, :update, :destroy]
  end

  resources :relationships, only: [:create,:destroy]
  resources :conversations, only: [:index, :create] do
      resources :messages, only: [:index, :create]
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  validates_presence_of :content
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment_and_topic, only:[:edit,:destroy,:update]

  def create
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    respond_to do |format|
      if @comment.save
        @comment = @topic.comments.build #jsでformを再描画するためのリセット
        format.html {render "topics/show"}
        format.js {render :index}
      else
        @topics = Topic.all
        @comments = @topic.comments
        format.html {render "topics/show"}
        format.js {render :new}
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to topic_path(@topic), notice: "トピックのコメントを編集しました。"
    else
      render :edit
    end
  end

  def destroy
    respond_to do |format|
      @comment.destroy
      # format.html {redirect_to topic_path(@topic), notice: "コメントを削除しました。"}
      format.js {render :index}
    end
  end

  private
  def comment_params
      params.require(:comment).permit(:topic_id,:content)
  end

  def set_comment_and_topic
    @comment = Comment.find(params[:id])
    @topic = @comment.topic
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic,comment], remote: true ) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= comment.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% comment.errors.clear %>
  <% end %>
  <%= f.hidden_field :topic_id %>
  <div id="comment_input">
    <%= profile_img(current_user)%>
    <%= f.text_field :content, placeholder: "コメントする...", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit "コメント投稿", class: 'btn btn-primary btn-block'  %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <div class="comment_row">
        <small>
          <li>
            <div id="comment">
              <p class="left"><%= profile_img(comment.user) %></p>
              <p id="comment_detail">
                <%= comment.user.name %>
                <%= comment.content %>
              </p>
            </div>
            <% if current_user.id == comment.user.id %>
              <div id="comment_icons left">
                <%= link_to '', edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg" %>
                <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
              </div>
            <% end %>
          </li>
        </small>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <p id="notice"><%= notice %></p>
      <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= @comment.errors.count %>件のエラーがあります。</h2>
          <ul>
          <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for([@topic, @comment]) do |f| %>
        <h2>コメント編集画面</h2>
        <%= f.hidden_field :topic_id %>
        <div class="field">
          <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
        </div>
        <div class="actions">
          <%= f.submit "編集", class: 'btn btn-primary btn-block' %>
        </div>
      <% end %>
      <p class="center back">
        <%= link_to 'トピック詳細へ戻る', topic_path(@topic) %>
      </p>
  </div>
</div>

app/views/comments/index.js.erb
// エラーメッセージのリフレッシュのためにform部分を再描画
$("#comments_list").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$("#form_area").html("<%= j(render 'comments/form', { comment: @comment, topic: @topic }) %>")
$(':text').val('')

app/views/comments/new.js.erb
$("#comments_list").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$("#form_area").html("<%= j(render 'comments/form', { comment: @comment, topic: @topic }) %>")
$(':text').val('')