config/routes.rb
Rails.application.routes.draw do

  root "top#index"
  resources :topics, only: [:index, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create,:edit, :update, :destroy]
  end

  resources :relationships, only: [:create,:destroy]
  resources :conversations, only: [:index, :create] do
      resources :messages, only: [:index, :create]
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates_presence_of :content
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only:[:show, :edit, :update, :destroy]

  def index
    @topics = Topic.order('id desc')
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topics_path, notice: "トピックを投稿しました！"
    else
      @topics = Topic.all
      render :index
    end
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end

  def edit
  end

  def update
    if @topic.update(topics_params)
      redirect_to topics_path, notice: "トピックを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path, notice: "トピックを削除しました！"
  end

  private
  def topics_params
    params.require(:topic).permit(:content)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <p id="notice"><%= notice %></p>
    <h2>トピックを編集する</h2>
    <%= form_for(@topic) do |f| %>
      <% if @topic.errors.any? %>
        <div id="error_explanation">
          <h3><%= @topic.errors.count %>件のエラーがあります。</h3>
          <ul>
          <% @topic.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <p><%= f.text_field :content, class: 'form-control'%></p>
      <p><%= f.submit '編集', class: 'btn btn-primary btn-block'%></p>
    <% end %>
    <p class="center back">
      <%= link_to 'トピック一覧へ戻る', topics_path %>
    </p>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h1>トピック一覧画面</h1>
    <p id="notice"><%= notice %></p>
    <% if @topic.errors.any? %>
      <div id="error_explanation">
        <h2><%= @topic.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div id="new_topic">
    <%= form_for(@topic, html: {class: 'topic_form'}) do |f| %>
      <div class="topic_input">
        <%= profile_img(current_user)%>
        <%= f.text_field :content, class: 'form-control', placeholder: "今なにしてる？" %><br>
      </div>
      <%= f.submit '投稿', class: 'btn btn-primary btn-block'%><br>
    <% end %>
    </div>
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="user_info">
          <div class="user_img">
            <%= profile_img(topic.user)%>
          </div>
          <div class="user_info_child">
            <%= topic.user.name%><br/>
            <small><%= topic.created_at %>に投稿</small><br>
          </div>
        </div>
        <div class="content">
          <%= topic.content %><br>
        </div>
      </div>
      <div class="icons">
        <%= link_to topic_path(topic) do%>
          <strong>詳細</strong>
        <% end %>
        <% if topic.user_id == current_user.id %>
          <%= link_to '', edit_topic_path(topic), class: "fa fa-pencil-square-o fa-lg" %>
          <%= link_to '', topic_path(topic), class: "fa fa-trash-o fa-lg", method: :delete, data: { confirm: '本当に削除していいですか？' } %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <div id="show_topic">
      <div class="user_info">
          <div class="user_img">
            <%= profile_img(@topic.user)%>
          </div>
          <div class="user_info_child">
            <%= @topic.user.name%><br/>
            <small><%= @topic.created_at %>に投稿</small><br>
          </div>
      </div>
      <div class="content">
          <%= @topic.content %><br>
      </div>
    </div>
    <div id="comments_area">
      <div id="comments_list">
        <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
      </div>
      <div id="form_area">
        <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
      </div>
    </div>
  <p class="center back">
    <%= link_to 'トピック一覧へ戻る', topics_path %>
  </p>
  </div>
</div>