config/routes.rb
Rails.application.routes.draw do

  root "top#index"
  resources :topics, only: [:index, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create,:edit, :update, :destroy]
  end

  resources :relationships, only: [:create,:destroy]
  resources :conversations, only: [:index, :create] do
      resources :messages, only: [:index, :create]
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kaohon</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class='<%= "#{controller.controller_name}" %>'>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <span class="kaohon_logo">
            <%= link_to root_path, class: "navbar-brand" do %>
              <%= image_tag("kaohon.png", :alt => "kaohon_logo") %>
            <% end %>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">メニュー<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "トップ", root_path %></li>
                  <li><%= link_to "トピック一覧", topics_path %></li>
                  <li><%= link_to 'ユーザー一覧', users_path if user_signed_in? %></li>
                  <li><%= link_to "メッセージ", conversations_path %></li>
                </ul>
              </li>
              <% if user_signed_in? %>
                <li><%= link_to 'マイページ', edit_user_registration_path %></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to 'ログイン', new_user_session_path  %></li>
                <li><%= link_to 'サインアップ', new_user_registration_path %></li>
              <% end %>
            </ul><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </div>
      </nav>
    </header>

    <%= yield %>

    <footer>
      <p>This web-site is made by Naruhiko Nojiri</p>
    </footer>
  </body>
</html>